networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24

services:
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice_shop
    hostname: juice.shop
    networks:
      backend:
        ipv4_address: 10.10.10.100
    ports:
      - "3000:3000"
    restart: unless-stopped

  nginx-modsec:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-modsec
    networks:
      backend:
        ipv4_address: 10.10.10.200
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Tạo volume cho các file log để fail2ban có thể đọc
      - ./logs:/var/log/nginx
      # Volume cho thư mục cấu hình fail2ban (tùy chọn, để dễ dàng cập nhật)
      - ./fail2ban:/etc/fail2ban
    depends_on:
      - juice-shop
    restart: unless-stopped
    # Sử dụng privileged mode để fail2ban có thể cập nhật iptables
    privileged: true