networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24

services:
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice_shop
    hostname: juice.shop
    networks:
      backend:
        ipv4_address: 10.10.10.100
    ports:
      - "3000:3000"
    restart: unless-stopped

  nginx-modsec:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-modsec
    networks:
      backend:
        ipv4_address: 10.10.10.200
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs:/var/log/nginx
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - juice-shop
    restart: unless-stopped
    privileged: true